name: neovide # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1-snap'
# TODO: change to this before committing:
# version: git
summary: The snappiest vim editor you are likely to find.
description: |
  This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements,
  but it should act functionally like the terminal UI.

grade: devel # must be 'stable' to release into candidate/stable channels
# TODO: Try getting it to build and run in strict confinement. In classic
# confinement, the host system can be accessed, so I really don't know what
# build-packages and stage-packages are really required.
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  nvim-bin:
    interface: content
    content: nvim-bin
    target: $SNAP/usr/local
    default-provider: nvim

parts:
  neovide:
    plugin: rust
    source: .
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcb-composite0-dev

apps:
  neovide:
    environment:
      PATH: ${PATH}:${SNAP}/usr/local/bin
    command: bin/neovide
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - x11
